name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ --no-default-features, --all-features ]
    steps:
      - uses: actions/checkout@v4
      - name: update toolchain
        run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}
      - name: rustfmt
        run: cargo fmt -- --check --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate,format_code_in_doc_comments=true"
      - name: clippy
        run: cargo clippy ${{ matrix.features }} --all-targets -- -D warnings
      - name: test
        run: cargo test ${{ matrix.features }}
      - name: check doc
        run: cargo doc
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  loom:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy
        env:
          RUSTFLAGS: "--cfg loom"
      - name: test except basic_notification
        run: cargo test --tests --release -- --skip basic_notification
        env:
          RUSTFLAGS: "--cfg loom -C debug_assertions"
          LOOM_MAX_PREEMPTIONS: 3
      - name: test basic_notification
        run: cargo test --tests --release
        env:
          RUSTFLAGS: "--cfg loom -C debug_assertions"
          LOOM_MAX_PREEMPTIONS: 2
      - name: check orderings
        run: python3 check_ordering.py

  compute-miri-seeds:
    runs-on: ubuntu-latest
    outputs:
      seeds: ${{ steps.compute-seeds.outputs.seeds }}
    steps:
      - id: compute-seeds
        run: python3 -c "print('seeds=' + str([f'{i}..{i+$TOTAL//$RUNNERS}' for i in range(0,$TOTAL,$TOTAL//$RUNNERS)]))" >> $GITHUB_OUTPUT
        env:
          TOTAL: 2048
          RUNNERS: 32

  miri:
    needs: [ test, compute-miri-seeds ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        seeds: ${{ fromJson(needs.compute-miri-seeds.outputs.seeds) }}
    steps:
      - uses: actions/checkout@v4
      - name: install miri
        run: rustup install nightly && rustup +nightly component add miri
      - uses: Swatinem/rust-cache@v2
      - name: miri
        run: cargo +nightly miri test --tests
        env:
          MIRIFLAGS: -Zmiri-many-seeds=${{ matrix.seeds }} -Zmiri-compare-exchange-weak-failure-rate=0

  benchmark:
    needs: test
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: benchmark
        run: cargo bench -- --min-time 0.1
